ENH: Allow reading DATE/TIME(s) from file(s)
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/datediff b/bin/datediff
--- a/bin/datediff
+++ b/bin/datediff
@@ -1,6 +1,7 @@
 #!/bin/bash
 # Source: http://unix.stackexchange.com/a/24636/18876
 # See also: dateutils.ddiff
+set -o pipefail
 shopt -qs extglob
 
 : ${DATE:=date}
@@ -17,7 +18,7 @@ now, and print it in flexible units depending on the magnitude of the
 difference.
 HELPDESCRIPTION
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" "... [-o|--output ${availableOutputFormats}] $prefixSuffixArgs [-a|--absolute] [--no-direction|DATE|TIME] DATE|TIME"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "... [-o|--output ${availableOutputFormats}] $prefixSuffixArgs [-a|--absolute] [--no-direction|DATE|TIME] -f|--file FILE [-f ...]|DATE|TIME"
     echo
     cat <<HELPDESCRIPTION
 Print the passed difference in seconds or days in flexible units depending on
@@ -33,14 +34,14 @@ SUFFIX may be 's' for seconds (the default), 'm' for minutes, 'h' for hours, 'd'
 for days, 'w' for weeks, 'mo' for months, 'y' for years, 'g' for generations.
 HELPDESCRIPTION
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '... --newer|--older|-lt|-le|-eq|-ne|-ge|-gt AGE[SUFFIX] [-a|--absolute] DATE|TIME [DATE|TIME]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '... --newer|--older|-lt|-le|-eq|-ne|-ge|-gt AGE[SUFFIX] [-a|--absolute] -f|--file FILE [-f ...]|DATE|TIME [DATE|TIME]'
     echo
     cat <<HELPDESCRIPTION
 Test whether the difference falls inside / outside TIMESLOT. TIMESLOT can be one
 of second|minute|hour|day|week|month|year.
 HELPDESCRIPTION
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '... -w|--within|-W|--outside s[econd]|m[inute]|h[our]|d[ay]|w[eek]|mo[nth]|y[ear] DATE|TIME [DATE|TIME]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '... -w|--within|-W|--outside s[econd]|m[inute]|h[our]|d[ay]|w[eek]|mo[nth]|y[ear] -f|--file FILE [-f ...]|DATE|TIME [DATE|TIME]'
 }
 printUsage()
 {
@@ -70,6 +71,10 @@ whereas "-le 1d" would yield true as long as the actual difference is within
 			differences.
     --prefix PREFIX	Put PREFIX before the output.
     --suffix SUFFIX	Append SUFFIX at the end.
+    --file|-f FILE	Read DATE(s) / TIME(s) (one per line, possibly followed
+			by tab-separated other content, which is taken over to
+			the output) from FILE. These are then each compared to
+			now / the passed DATE / TIME.
 
 EXIT STATUS:
     0	Complete success.
@@ -128,6 +133,8 @@ prefix=
 suffix=
 spanCompareOp=
 formatCompareOp=
+typeset -a filespecs=()
+dateArgOffset=1
 while [ $# -ne 0 ]
 do
     case "$1" in
@@ -150,18 +157,25 @@ do
 	--within|-w)	shift; parseTimeslot "${1:?}"; formatCompareOp='='; shift;;
 	--outside|-W)	shift; parseTimeslot "${1:?}"; formatCompareOp='!='; shift;;
 
+	--file|-f)	shift; filespecs+=("${1:?}"); shift; dateArgOffset=0;;
 	--)		[ "$hasDifference" ] || shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
+if [ "$hasDifference" ] && [ ${#filespecs[@]} -gt 0 ]; then
+    echo 'ERROR: Cannot combine -s|--seconds|-d|--days with -f|--file.'
+    echo
+    printUsage "$0"
+    exit 2
+fi >&2
 if [ -n "$spanCompareOp" ] || [ -n "$formatCompareOp" ]; then
     if [ "$hasDifference" ]; then
 	echo 'ERROR: Cannot combine -s|--seconds|-d|--days with --newer|--older|-lt|-le|-eq|-ne|-ge|-gt|--within|-w|--outside|-W.'
 	echo
 	printUsage "$0"
 	exit 2
-    elif [ $# -lt 1 -o $# -gt 2 ]; then
+    elif (($# < dateArgOffset || $# > dateArgOffset + 1)); then
 	printUsage "$0"
 	exit 2
     fi
@@ -175,7 +189,7 @@ elif [ -n "$daysDiff" ]; then
 	printUsage "$0"
 	exit 2
     fi
-elif [ $# -lt 1 -o $# -gt 2 ]; then
+elif (($# < dateArgOffset || $# > dateArgOffset + 1)); then
     printUsage "$0"
     exit 2
 fi >&2
@@ -384,4 +398,11 @@ diffOneDate()
     return $status
 }
 
-diffOneDate "$@"
+if [ ${#filespecs[@]} -gt 0 ]; then
+    cat -- "${filespecs[@]}" | while IFS=$'\t' read -r dateOrTime addendum || [ -n "$dateOrTime" ]
+    do
+	diffOneDate "$@" "$dateOrTime"
+    done
+else
+    diffOneDate "$@"
+fi
