ENH: Allow TIMESLOT for --{newer,older} as well
So that it can serve as a past interval of either arbitrary AGE or within a TIMESLOT that's accepted by a client, with any future dates being accepted unconditionally. That's what many of my clients require.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/datediff b/bin/datediff
--- a/bin/datediff
+++ b/bin/datediff
@@ -17,9 +17,10 @@ readonly generalArgs='[-u|--utc|--universal]'
 readonly availableOutputFormats='s[econd[s]]|m[inute[s]]|h[our[s]]|d[ay[s]]|w[eek[s]]|mo[nth[s]]|y[ear[s]]|g[eneration[s]]|whole-units|smallest-unit|best-unit|largest-unit|precise|all|textform'
 readonly precisionArgs='[--prefer-clock] [--long-units] [--precision|-p N|[U|Z][.N](w|d|h|m|s) | --precision-width|-P WIDTH] [-w|--width [+]WIDTH]'
 readonly prefixSuffixArgs='[--prefix PREFIX [--prefix ...]] [--suffix SUFFIX [--suffix ...]]'
-readonly newerOlderArgs='--newer|--older [-]AGE[SUFFIX]'
+readonly timeslotParameters='s[econd]|m[inute]|h[our]|d[ay]|w[eek]|mo[nth]|y[ear]'
+readonly newerOlderArgs='--newer|--older [-]AGE[SUFFIX]|TIMESLOT'
 readonly comparisonArgs='-lt|-le|-eq|-ne|-ge|-gt [-]AGE[SUFFIX] [-a|--absolute]'
-readonly timeslotArgs='-w|--within|-W|--outside s[econd]|m[inute]|h[our]|d[ay]|w[eek]|mo[nth]|y[ear]'
+readonly timeslotArgs='-w|--within|-W|--outside TIMESLOT'
 getShortUsage()
 {
     case "$1" in
@@ -68,7 +69,11 @@ HELPDESCRIPTION
     echo
     cat <<HELPDESCRIPTION
 Test whether ${DATEDIFF_WHAT} falls inside / outside TIMESLOT.
-TIMESLOT can be one of second|minute|hour|day|week|month|year.
+Use --newer|--older instead of --within|--outside if you want future dates /
+dates where the second passed DATE|TIME is greater than the first to always
+succeed the comparision; i.e. if you only care about falling outside the
+timeslot in the past.
+TIMESLOT can be one of ${timeslotParameters}.
 HELPDESCRIPTION
     echo
     printf 'Usage: %q %s\n' "$DATEDIFF_COMMAND" "... $timeslotArgs $DATEDIFF_INPUT_ARGS"
@@ -160,10 +165,25 @@ parseTimeslot()
     esac
 }
 isNegated=
+spanCompareOp=
+formatCompareOp=
+combinedCompareOp='-eq'
 parseAgeOrTimeslot()
 {
-    parseAge "$@" || { printf >&2 'ERROR: Invalid AGE: "%s".\n\n' "$1"; printUsage "$0" >&2; exit 2; }
-    let age=-age
+    local potentialSpanCompareOp="${1:?}"; shift
+    local potentialCombinedCompareOp="${1:?}"; shift
+
+    if parseTimeslot "$@"; then
+	spanCompareOp='-ge'
+	age=0
+	formatCompareOp='='
+	combinedCompareOp="$potentialCombinedCompareOp"
+    elif parseAge "$@"; then
+	spanCompareOp="$potentialSpanCompareOp"
+	let age=-age
+    else
+	return 1
+    fi
     isNegated=t
 }
 
@@ -179,8 +199,6 @@ outputFormat="$DATEDIFF_OUTPUT_FORMAT"
 typeset -a secondsToDurationArgs=()
 prefix=
 suffix=
-spanCompareOp=
-formatCompareOp=
 typeset -a filespecs=()
 dateArgOffset=1
 option() { :; }
@@ -221,8 +239,8 @@ do
 	--seconds|-s)	shift; ensureSingleDifference; secondsDiff="${1:?}"; shift; hasDifference=t; parameter;;
 	--days|-d)	shift; ensureSingleDifference; daysDiff="${1:?}"; shift; hasDifference=t; parameter;;
 
-	--newer)	shift; parseAgeOrTimeslot "${1:?}"; shift; spanCompareOp=-gt; parameter;;
-	--older)	shift; parseAgeOrTimeslot "${1:?}"; shift; spanCompareOp=-lt; parameter;;
+	--newer)	shift; parseAgeOrTimeslot -gt -eq "${1:?}" || { printf >&2 'ERROR: Invalid AGE or TIMESLOT: "%s".\n\n' "$1"; printUsage "$0" >&2; exit 2; }; shift; parameter;;
+	--older)	shift; parseAgeOrTimeslot -lt -ne "${1:?}" || { printf >&2 'ERROR: Invalid AGE or TIMESLOT: "%s".\n\n' "$1"; printUsage "$0" >&2; exit 2; }; shift; parameter;;
 	-lt|-le|-eq|-ne|-ge|-gt)
 			spanCompareOp="$1"; shift; parseAge "${1:?}" || { printf >&2 'ERROR: Invalid AGE: "%s".\n\n' "$1"; printUsage "$0" >&2; exit 2; }; shift; parameter;;
 	--within|-w)	shift; parseTimeslot "${1:?}" || { printf >&2 'ERROR: Invalid TIMESLOT: "%s".\n\n' "$1"; printUsage "$0" >&2; exit 2; }; formatCompareOp='='; shift; parameter;;
@@ -242,7 +260,7 @@ if [ "$hasDifference" ] && [ ${#filespecs[@]} -gt 0 ]; then
     printUsage "$0"
     exit 2
 elif [ "$isNegated" ] && [ "$isAbsolute" ]; then
-    echo 'ERROR: Cannot combine -a|--absolute with --newer|--older; use -lt|-le|-eq|-ne|-ge|-gt instead.'
+    echo 'ERROR: Cannot combine -a|--absolute with --newer|--older; use -lt|-le|-eq|-ne|-ge|-gt / --within|-w|--outside|-W instead.'
     echo
     printUsage "$0"
     exit 2
@@ -378,23 +396,28 @@ diffOneDate()
     typeset -a diffInUnits=()
     local status=0
     if [ -n "$spanCompareOp" ] || [ -n "$formatCompareOp" ]; then
+	local secondsDiff=
 	parseDates "$@" || return $?
-	if \
-	    if [ -n "$formatCompareOp" ]; then
-		[ "$d1" $formatCompareOp "$d2" ]
-	    else
-		local secondsDiff=$((d2 - d1))
-		[ "$isAbsolute" ] \
-		    && secondsDiff=$((secondsDiff < 0 ? -secondsDiff : secondsDiff))
-		[ $secondsDiff ${spanCompareOp:?} $age ]
-	    fi
+	{
+	    [ -n "$formatCompareOp" ] \
+		&& [ "$d1" $formatCompareOp "$d2" ]
+	} || {
+		[ -n "$spanCompareOp" ] && {
+		    [ "$timeformat" = '%s' ] || timeformat='%s' parseDates "$@" || return $?
+		    secondsDiff=$((d2 - d1))
+		    [ "$isAbsolute" ] \
+			&& secondsDiff=$((secondsDiff < 0 ? -secondsDiff : secondsDiff))
+		    [ $secondsDiff ${spanCompareOp:?} $age ]
+		}
+	}; status=$?
+	if [ $status $combinedCompareOp 0 ];
 	then
 	    return 0
 	else
 	    isOutput || return 1
-	    if [ -n "$formatCompareOp" ]; then
+	    if [ -z "$secondsDiff" ]; then
 		timeformat='%s' parseDates "$@"
-		local secondsDiff=$((d2 - d1))
+		secondsDiff=$((d2 - d1))
 	    fi
 	    status=1
 	fi
